### ISSUE TITLE
:Dash closes vim 

### ISSUE THREAD

**Issue by shinokada** [rizzatti/dash.vim#13]
When I type :Dash. it opens Dash app and shows the doc. But it closes the vim. What am I doing wrong here?

**Comment by rizzatti** [comment]
@jottr Hi
I think you are referring to Dash being activated and vim going to the background, right? If so, you can look at ```:help DashConfig_activate```.
Setting ```g:dash_activate = 1``` in .vimrc will change that behavior.

**Comment by jottr** [comment]
I think I found the culprit. I had `set shell /bin/bash -i` in my `.vimrc`. This caused vim to be suspended when calling Dash. 
Thx for pointing me towards `dash_activate`. 
Issue can be closed.
