### ISSUE TITLE
Call Dash without activating it

### ISSUE THREAD

**Issue by Kapeli** [rizzatti/dash.vim#41]
dash.vim calls Dash by opening a `dash://` URL. The problem is that the system forces Dash to become active when this URL is opened.

Currently, this is not an issue. However, a future update of Dash will add support for iOS remotes. While an iOS remote is connected, extensions are redirected to it directly and Dash on OS X is not shown at all. Unfortunately there's no way for me to prevent the system from activating Dash when you open the `dash://` URL.

Instead of doing this:
```
open dash://query
```

Can you do this?
```
open -g dash://query
```

The `-g` causes Dash to not get activated if it does not want to and the user experience is a lot better as the active app does not lose focus anymore.

It is safe to make this change as soon as possible (no need to wait for a Dash update), as the current version of Dash already knows to activate itself if it needs to.

**Comment by Kapeli** [comment]
@rizzatti Can you take a look at this when you get a chance?

**Comment by rizzatti** [comment]
I'll update all the issues this weekend. Sorry for the delay, @Kapeli.

**Comment by rizzatti** [comment]
Fixed.

**Comment by Kapeli** [comment]
Thank you! :purple_heart:
