### ISSUE TITLE
How to prevent Dash activation on mouse click

### ISSUE THREAD

**Issue by dylansm** [rizzatti/dash.vim#44]
Sorry if I missed it but I can't find a way to prevent a mouse click in Vim from popping open Dash. I like to have the variable for mouse set as mouse=a in my .vimrc. Is there an easy way to configure this? Thanks.

**Comment by rizzatti** [comment]
@dylansm I'm sorry but I couldn't reproduce this problem neither in vim or macvim. There might be some interaction with a third plugin that could be causing you to see this strange behaviour.
You could try leaving just dash.vim and your plugin manager running and check if you still have the same problem.

**Comment by dylansm** [comment]
Thanks, I had to uninstall it. Not sure why I was having so many problems.
