### ISSUE TITLE
Hope that system call of uname get removed

### ISSUE THREAD

**Issue by chemzqm** [rizzatti/dash.vim#48]
Dash.vim would add nearly 15ms  to my vim start time, it's my second slowest plugin.
When I get the unname check removed,  the loading time would be less than 1ms.
I think it's not necessary to avoid loading the script by check the uname, it should be fine if the script get loaded but could not works.  
This check slows down vim instead of make vim faster.

**Comment by rizzatti** [comment]
Removed.
