### ISSUE TITLE
Info video about Dash plugin on YouTube

### ISSUE THREAD

**Issue by petrowsky** [rizzatti/dash.vim#49]
Love the plugin. Sorry about using the issue queue. Just wanted to let you know.

https://www.youtube.com/watch?v=trGEGhitN4A&feature=youtu.be

**Comment by Anzumana** [comment]
Great video to get started using the Plugin. Thanks for sharing.
If you do this http://stackoverflow.com/questions/3997078/how-to-paste-yanked-text-into-vim-command-line
You can do you want even with dashed words

**Comment by Anzumana** [comment]
@petrowsky make a pull request to the readme with a link to the video and the little tip i found to make it work even better.
