### ISSUE TITLE
Dash.vim and neocomplete.vim

### ISSUE THREAD

**Issue by slabko** [rizzatti/dash.vim#50]
I'm wondering if there are any ideas about integrating Dash database with neocomplete.vim. It seems like Dash.app could be a really good source of keywords for autocompletion, but I didn't find anything about it.

**Comment by rizzatti** [comment]
Hi @slabko.

The way dash.vim works right now is quite simple, figuring out the possible types of documentation one might be looking for depending on the filetype one is using, and allowing some configuration around this.
But after that, it completely delegates the search to Dash.app.

The thing is, the plugin API from Dash.app does not grant access to it's internal data. It's a one way street.

**Comment by slabko** [comment]
He @rizzatti 

Thank you very much for the response. One more question about it - I saw that was actually possible to get more information from Dash. A simple example could be Alfred, where, if you type dash and part of the searching text, it shows dropdown with matching names. I thought, if I want to implement such a thing for VIM, there should be an API of such kind, which gives the matching result for my search outside the app.

**Comment by rizzatti** [comment]
@slabko Thanks for letting me know. I'll look into how that integration works.
