### ISSUE TITLE
Visual selection?

### ISSUE THREAD

**Issue by stellarhoof** [rizzatti/dash.vim#59]
Currently `<Plug>DashSearch` only takes the word under the cursor. Consider making this an operator so we can use text objects on it and also visual selections.

**Comment by JGShaw** [comment]
@stellarhoof I added the ability to search by visual selection in #58, its probably not the best way to do it but it seems to work for me.

**Comment by stellarhoof** [comment]
@JGShaw Thank you. This is fine.
